In [54]:
import polars as pl
import altair

In [ ]:
"""
Exploration conclusions:
    1. Cols [contract_desc] and [nip] are not atomic - data is paired in a form of comma delimited strings
        
        Example:
        
        [contract_desc]                     [nip]
        "company_a, company_b, company_c" | "6791921738, 8691984858, 78236424843"
        
        Decisions:
        
        There are 14 rows where after splitting data, lengths in columns don't match. These will be removed from further analysis. 
"""

'\nExploration conclusions:\n    1. Cols [contract_desc] and [nip] are not atomic - data is paired in a form of comma delimited strings\n\n        Example:\n\n        [contract_desc]                     [nip]\n        "company_a, company_b, company_c" | "6791921738, 8691984858, 78236424843"\n'

In [61]:
df = pl.read_excel(r"data\umk_contracts_202*.xlsx")

df = df.rename({
    'Lp': 'idx',
    'rok_plik': 'year_filename',
    'Numer w rejestrze': 'registry',
    'Nazwa Kontrahenta ': 'contractor_name',
    'NIP': 'nip',
    'Kwota złotych brutto': 'gross_total_pln',
    'Data obowiązywania od': 'date_valid_from',
    'Data obowiązywania do': 'date_valid_to',
    'Data zawarcia': 'date_contract_signed',
    'Przedmiot umowy': 'contract_desc',
    'Jedn. Realizująca': 'administrative_unit'
})

from types import SimpleNamespace

_names = SimpleNamespace({col: col for col in df.columns})

C:\Users\Manager\AppData\Local\Temp\ipykernel_20504\1031874544.py:1: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  df = pl.read_excel(r"data\umk_contracts_202*.xlsx")

In [ ]:
"""
1. Cols [contract_desc] and [nip] are not atomic - data is paired in a form of comma delimited strings
    
    Example:
    
    [contract_desc]                     [nip]
    "company_a, company_b, company_c" | "6791921738, 8691984858, 78236424843"
    
    Decisions:
    
    There are 14 rows where after splitting data, lengths in columns don't match. These will be removed from further analysis. 
"""

df = (
    df
    .select(
        pl.col(_names.idx, _names.contractor_name, _names.nip)
    )
    .with_columns(
        pl.col(_names.nip).str.contains(',').alias("contains_comma")
    )
    # .select(
    #     pl.col("contains_comma").sum()
    # )
    .filter(
        pl.col("contains_comma")
    )
    .with_columns(
        pl.col(_names.contractor_name).str.split(','),
        pl.col(_names.nip).str.split(',')
    )
    .with_columns(
        abs(pl.col(_names.contractor_name).list.len().cast(pl.Int64) - pl.col(_names.nip).list.len().cast(pl.Int64)).alias("diff_len") #cast to Int64 or we get underflow
    )
    .filter(
        pl.col("diff_len") != 0
    )
)

shape: (17_646, 11)
┌─────┬─────┬─────┬─────┬───┬─────┬─────┬─────┬─────┐
│ idx ┆ yea ┆ reg ┆ con ┆ … ┆ dat ┆ dat ┆ con ┆ adm │
│ --- ┆ r_f ┆ ist ┆ tra ┆   ┆ e_v ┆ e_c ┆ tra ┆ ini │
│ i64 ┆ ile ┆ ry  ┆ cto ┆   ┆ ali ┆ ont ┆ ct_ ┆ str │
│     ┆ nam ┆ --- ┆ r_n ┆   ┆ d_t ┆ rac ┆ des ┆ ati │
│     ┆ e   ┆ str ┆ ame ┆   ┆ o   ┆ t_s ┆ c   ┆ ve_ │
│     ┆ --- ┆     ┆ --- ┆   ┆ --- ┆ ign ┆ --- ┆ uni │
│     ┆ i64 ┆     ┆ str ┆   ┆ str ┆ ed  ┆ str ┆ t   │
│     ┆     ┆     ┆     ┆   ┆     ┆ --- ┆     ┆ --- │
│     ┆     ┆     ┆     ┆   ┆     ┆ str ┆     ┆ str │
╞═════╪═════╪═════╪═════╪═══╪═════╪═════╪═════╪═════╡
│ 1   ┆ 202 ┆ -W/ ┆ TRA ┆ … ┆ 202 ┆ 202 ┆ USŁ ┆ AU  │
│     ┆ 3   ┆ IV- ┆ NSL ┆   ┆ 3-1 ┆ 3-1 ┆ UGA ┆     │
│     ┆     ┆ B/2 ┆ ATI ┆   ┆ 0-0 ┆ 0-0 ┆ TŁU ┆     │
│     ┆     ┆ 91/ ┆ ON  ┆   ┆ 4   ┆ 3   ┆ MAC ┆     │
│     ┆     ┆ AU/ ┆ STR ┆   ┆     ┆     ┆ ZEN ┆     │
│     ┆     ┆ 4/2 ┆ EET ┆   ┆     ┆     ┆ IA  ┆     │
│     ┆     ┆ 023 ┆ JAS ┆   ┆     ┆     ┆ KON ┆     │
│     ┆     ┆     ┆ IUK ┆   ┆     ┆     ┆ SEK ┆     │
│     ┆     ┆     ┆ IEW ┆   ┆     ┆     ┆ UTY ┆     │
│     ┆     ┆     ┆ ICZ ┆   ┆     ┆     ┆ WNE ┆     │
│     ┆     ┆     ┆ -   ┆   ┆     ┆     ┆ GO  ┆     │
│     ┆     ┆     ┆ SZC ┆   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ ZUR ┆   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ EK  ┆   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ SP. ┆   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ Z   ┆   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ O.… ┆   ┆     ┆     ┆     ┆     │
│ 2   ┆ 202 ┆ -W/ ┆ POL ┆ … ┆ 202 ┆ 202 ┆ PUB ┆ AU  │
│     ┆ 3   ┆ IV- ┆ SKA ┆   ┆ 3-1 ┆ 3-0 ┆ LIK ┆     │
│     ┆     ┆ B/2 ┆ PRE ┆   ┆ 2-2 ┆ 9-1 ┆ ACJ ┆     │
│     ┆     ┆ 76/ ┆ SS  ┆   ┆ 0   ┆ 8   ┆ A   ┆     │
│     ┆     ┆ AU/ ┆ SP. ┆   ┆     ┆     ┆ NA  ┆     │
│     ┆     ┆ 3/2 ┆ Z   ┆   ┆     ┆     ┆ ZLE ┆     │
│     ┆     ┆ 023 ┆ O.O ┆   ┆     ┆     ┆ CEN ┆     │
│     ┆     ┆     ┆ .   ┆   ┆     ┆     ┆ IE  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ OBW ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ IES ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ZCZ ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ EŃ  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ W   ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ PRA ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ SIE ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ COD ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ZIE ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ …   ┆     │
│ 3   ┆ 202 ┆ -W/ ┆ AGO ┆ … ┆ 202 ┆ 202 ┆ PUD ┆ AU  │
│     ┆ 3   ┆ IV- ┆ RA  ┆   ┆ 3-0 ┆ 3-0 ┆ LIK ┆     │
│     ┆     ┆ B/2 ┆ S.A ┆   ┆ 2-0 ┆ 1-1 ┆ ACJ ┆     │
│     ┆     ┆ 0/A ┆ .   ┆   ┆ 3   ┆ 9   ┆ A   ┆     │
│     ┆     ┆ U/1 ┆     ┆   ┆     ┆     ┆ ODW ┆     │
│     ┆     ┆ /20 ┆     ┆   ┆     ┆     ┆ IES ┆     │
│     ┆     ┆ 23  ┆     ┆   ┆     ┆     ┆ ZCZ ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ EŃ  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ W   ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ PRA ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ SIE ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ COD ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ZIE ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ NNE ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ J O ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ZAS ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ IE… ┆     │
│ 4   ┆ 202 ┆ -W/ ┆ PBS ┆ … ┆ 202 ┆ 202 ┆ WYK ┆ AU  │
│     ┆ 3   ┆ IV- ┆ ERV ┆   ┆ 3-0 ┆ 3-0 ┆ ONA ┆     │
│     ┆     ┆ B/1 ┆ ICE ┆   ┆ 5-3 ┆ 4-2 ┆ NIE ┆     │
│     ┆     ┆ 29/ ┆ S.C ┆   ┆ 1   ┆ 6   ┆ KOP ┆     │
│     ┆     ┆ AU/ ┆ KAM ┆   ┆     ┆     ┆ ERT ┆     │
│     ┆     ┆ 2/2 ┆ IL  ┆   ┆     ┆     ┆ Z   ┆     │
│     ┆     ┆ 023 ┆ WYK ┆   ┆     ┆     ┆ NAD ┆     │
│     ┆     ┆     ┆ ROT ┆   ┆     ┆     ┆ RUK ┆     │
│     ┆     ┆     ┆ A,  ┆   ┆     ┆     ┆ IEM ┆     │
│     ┆     ┆     ┆ KRZ ┆   ┆     ┆     ┆ WRA ┆     │
│     ┆     ┆     ┆ YSZ ┆   ┆     ┆     ┆ Z Z ┆     │
│     ┆     ┆     ┆ TOF ┆   ┆     ┆     ┆ DOS ┆     │
│     ┆     ┆     ┆ PAW ┆   ┆     ┆     ┆ TAW ┆     │
│     ┆     ┆     ┆ ŁOW ┆   ┆     ┆     ┆ Ą   ┆     │
│     ┆     ┆     ┆ SKI ┆   ┆     ┆     ┆     ┆     │
│ 5   ┆ 202 ┆ -W/ ┆ PBS ┆ … ┆ 202 ┆ 202 ┆ DZI ┆ AU  │
│     ┆ 3   ┆ I/5 ┆ ERV ┆   ┆ 3-1 ┆ 3-0 ┆ ERŻ ┆     │
│     ┆     ┆ 53/ ┆ ICE ┆   ┆ 2-3 ┆ 1-3 ┆ AWA ┆     │
│     ┆     ┆ AU/ ┆ S.C ┆   ┆ 1   ┆ 1   ┆ UŻĄ ┆     │
│     ┆     ┆ 1/2 ┆ KAM ┆   ┆     ┆     ┆ DZE ┆     │
│     ┆     ┆ 023 ┆ IL  ┆   ┆     ┆     ┆ NI  ┆     │
│     ┆     ┆     ┆ WYK ┆   ┆     ┆     ┆ AKO ┆     │
│     ┆     ┆     ┆ ROT ┆   ┆     ┆     ┆ PER ┆     │
│     ┆     ┆     ┆ A,  ┆   ┆     ┆     ┆ TUJ ┆     │
│     ┆     ┆     ┆ KRZ ┆   ┆     ┆     ┆ ĄCE ┆     │
│     ┆     ┆     ┆ YSZ ┆   ┆     ┆     ┆ GO  ┆     │
│     ┆     ┆     ┆ TOF ┆   ┆     ┆     ┆ PIT ┆     │
│     ┆     ┆     ┆ PAW ┆   ┆     ┆     ┆ NEY ┆     │
│     ┆     ┆     ┆ ŁOW ┆   ┆     ┆     ┆ BOW ┆     │
│     ┆     ┆     ┆ SKI ┆   ┆     ┆     ┆ ES  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ DI3 ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ …   ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ … ┆ …   ┆ …   ┆ …   ┆ …   │
│ 599 ┆ 202 ┆ -W/ ┆ MIĘ ┆ … ┆ 202 ┆ 202 ┆ WYN ┆ WT  │
│ 3   ┆ 5   ┆ XII ┆ DZY ┆   ┆ 5-0 ┆ 5-0 ┆ AJE ┆     │
│     ┆     ┆ /3/ ┆ NAR ┆   ┆ 5-1 ┆ 3-0 ┆ M   ┆     │
│     ┆     ┆ WT/ ┆ ODO ┆   ┆ 1   ┆ 7   ┆ PRZ ┆     │
│     ┆     ┆ 2/2 ┆ WE  ┆   ┆     ┆     ┆ EST ┆     │
│     ┆     ┆ 025 ┆ CEN ┆   ┆     ┆     ┆ RZE ┆     │
│     ┆     ┆     ┆ TRU ┆   ┆     ┆     ┆ NI  ┆     │
│     ┆     ┆     ┆ M   ┆   ┆     ┆     ┆ KON ┆     │
│     ┆     ┆     ┆ KUL ┆   ┆     ┆     ┆ FER ┆     │
│     ┆     ┆     ┆ TUR ┆   ┆     ┆     ┆ ENC ┆     │
│     ┆     ┆     ┆ Y   ┆   ┆     ┆     ┆ YJN ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ EJ  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ WRA ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ Z Z ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ZAP ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ LEC ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ZE… ┆     │
│ 599 ┆ 202 ┆ -W/ ┆ KRA ┆ … ┆ 202 ┆ 202 ┆ WYN ┆ WT  │
│ 4   ┆ 5   ┆ XII ┆ KÓW ┆   ┆ 5-0 ┆ 5-0 ┆ AJE ┆     │
│     ┆     ┆ /2/ ┆ 502 ┆   ┆ 2-1 ┆ 2-1 ┆ M   ┆     │
│     ┆     ┆ WT/ ┆ 0   ┆   ┆ 7   ┆ 1   ┆ PRZ ┆     │
│     ┆     ┆ 1/2 ┆ SP. ┆   ┆     ┆     ┆ EZ  ┆     │
│     ┆     ┆ 025 ┆ Z   ┆   ┆     ┆     ┆ GMK ┆     │
│     ┆     ┆     ┆ O.O ┆   ┆     ┆     ┆ ORA ┆     │
│     ┆     ┆     ┆ . W ┆   ┆     ┆     ┆ Z   ┆     │
│     ┆     ┆     ┆ LIK ┆   ┆     ┆     ┆ AGE ┆     │
│     ┆     ┆     ┆ WID ┆   ┆     ┆     ┆ NCJ ┆     │
│     ┆     ┆     ┆ ACJ ┆   ┆     ┆     ┆ Ę   ┆     │
│     ┆     ┆     ┆ I,  ┆   ┆     ┆     ┆ WIN ┆     │
│     ┆     ┆     ┆ WIN ┆   ┆     ┆     ┆ DMI ┆     │
│     ┆     ┆     ┆ DMI ┆   ┆     ┆     ┆ LL  ┆     │
│     ┆     ┆     ┆ LL  ┆   ┆     ┆     ┆ DZI ┆     │
│     ┆     ┆     ┆ SPÓ ┆   ┆     ┆     ┆ AŁA ┆     │
│     ┆     ┆     ┆ …   ┆   ┆     ┆     ┆ JĄC ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ Ą…  ┆     │
│ 599 ┆ 202 ┆ -W/ ┆ AGE ┆ … ┆ 202 ┆ 202 ┆ WYN ┆ WT  │
│ 5   ┆ 5   ┆ XII ┆ NCJ ┆   ┆ 5-1 ┆ 5-1 ┆ AJE ┆     │
│     ┆     ┆ /30 ┆ A   ┆   ┆ 1-1 ┆ 0-1 ┆ M W ┆     │
│     ┆     ┆ /WT ┆ ROZ ┆   ┆ 5   ┆ 0   ┆ DNI ┆     │
│     ┆     ┆ /13 ┆ WOJ ┆   ┆     ┆     ┆ U   ┆     │
│     ┆     ┆ /20 ┆ U   ┆   ┆     ┆     ┆ 15  ┆     │
│     ┆     ┆ 25  ┆ MIA ┆   ┆     ┆     ┆ LIS ┆     │
│     ┆     ┆     ┆ STA ┆   ┆     ┆     ┆ TOP ┆     │
│     ┆     ┆     ┆ KRA ┆   ┆     ┆     ┆ ADA ┆     │
│     ┆     ┆     ┆ KOW ┆   ┆     ┆     ┆ 202 ┆     │
│     ┆     ┆     ┆ A   ┆   ┆     ┆     ┆ 5   ┆     │
│     ┆     ┆     ┆ SPÓ ┆   ┆     ┆     ┆ R.  ┆     │
│     ┆     ┆     ┆ ŁKA ┆   ┆     ┆     ┆ PRZ ┆     │
│     ┆     ┆     ┆ Z   ┆   ┆     ┆     ┆ EST ┆     │
│     ┆     ┆     ┆ OGR ┆   ┆     ┆     ┆ RZE ┆     │
│     ┆     ┆     ┆ ANI ┆   ┆     ┆     ┆ NI  ┆     │
│     ┆     ┆     ┆ CZ… ┆   ┆     ┆     ┆ CE… ┆     │
│ 599 ┆ 202 ┆ -W/ ┆ MCS ┆ … ┆ 202 ┆ 202 ┆ ZAK ┆ WT  │
│ 6   ┆ 5   ┆ IV- ┆ WIT ┆   ┆ 5-0 ┆ 5-0 ┆ UP  ┆     │
│     ┆     ┆ B/8 ┆ OLD ┆   ┆ 4-1 ┆ 3-1 ┆ AUT ┆     │
│     ┆     ┆ 2/W ┆ ROM ┆   ┆ 5   ┆ 4   ┆ ORS ┆     │
│     ┆     ┆ T/1 ┆ ANI ┆   ┆     ┆     ┆ KIC ┆     │
│     ┆     ┆ /20 ┆ SZY ┆   ┆     ┆     ┆ H   ┆     │
│     ┆     ┆ 25  ┆ N   ┆   ┆     ┆     ┆ PIN ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ÓW  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ (27 ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ 50  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ SZT ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ .)  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ Z   ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ MOT ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ YWA ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ MI  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ KRA ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ K…  ┆     │
│ 599 ┆ 202 ┆ -W/ ┆ SO  ┆ … ┆ 202 ┆ 202 ┆ ZAP ┆ WT  │
│ 7   ┆ 5   ┆ I/2 ┆ BRI ┆   ┆ 5-1 ┆ 5-0 ┆ LAN ┆     │
│     ┆     ┆ 489 ┆ GHT ┆   ┆ 0-3 ┆ 5-2 ┆ OWA ┆     │
│     ┆     ┆ /WT ┆ SPÓ ┆   ┆ 1   ┆ 8   ┆ NIE ┆     │
│     ┆     ┆ /34 ┆ ŁKA ┆   ┆     ┆     ┆ I   ┆     │
│     ┆     ┆ /20 ┆ Z   ┆   ┆     ┆     ┆ REA ┆     │
│     ┆     ┆ 25  ┆ O.O ┆   ┆     ┆     ┆ LIZ ┆     │
│     ┆     ┆     ┆ .   ┆   ┆     ┆     ┆ ACJ ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ A   ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ KAM ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ PAN ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ II  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ INF ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ORM ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ACY ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ JNO ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ - … ┆     │
└─────┴─────┴─────┴─────┴───┴─────┴─────┴─────┴─────┘

In [66]:
df_temp = df #[200:300]
df_temp

shape: (17_646, 11)
┌─────┬─────┬─────┬─────┬───┬─────┬─────┬─────┬─────┐
│ idx ┆ yea ┆ reg ┆ con ┆ … ┆ dat ┆ dat ┆ con ┆ adm │
│ --- ┆ r_f ┆ ist ┆ tra ┆   ┆ e_v ┆ e_c ┆ tra ┆ ini │
│ i64 ┆ ile ┆ ry  ┆ cto ┆   ┆ ali ┆ ont ┆ ct_ ┆ str │
│     ┆ nam ┆ --- ┆ r_n ┆   ┆ d_t ┆ rac ┆ des ┆ ati │
│     ┆ e   ┆ str ┆ ame ┆   ┆ o   ┆ t_s ┆ c   ┆ ve_ │
│     ┆ --- ┆     ┆ --- ┆   ┆ --- ┆ ign ┆ --- ┆ uni │
│     ┆ i64 ┆     ┆ str ┆   ┆ str ┆ ed  ┆ str ┆ t   │
│     ┆     ┆     ┆     ┆   ┆     ┆ --- ┆     ┆ --- │
│     ┆     ┆     ┆     ┆   ┆     ┆ str ┆     ┆ str │
╞═════╪═════╪═════╪═════╪═══╪═════╪═════╪═════╪═════╡
│ 1   ┆ 202 ┆ -W/ ┆ TRA ┆ … ┆ 202 ┆ 202 ┆ USŁ ┆ AU  │
│     ┆ 3   ┆ IV- ┆ NSL ┆   ┆ 3-1 ┆ 3-1 ┆ UGA ┆     │
│     ┆     ┆ B/2 ┆ ATI ┆   ┆ 0-0 ┆ 0-0 ┆ TŁU ┆     │
│     ┆     ┆ 91/ ┆ ON  ┆   ┆ 4   ┆ 3   ┆ MAC ┆     │
│     ┆     ┆ AU/ ┆ STR ┆   ┆     ┆     ┆ ZEN ┆     │
│     ┆     ┆ 4/2 ┆ EET ┆   ┆     ┆     ┆ IA  ┆     │
│     ┆     ┆ 023 ┆ JAS ┆   ┆     ┆     ┆ KON ┆     │
│     ┆     ┆     ┆ IUK ┆   ┆     ┆     ┆ SEK ┆     │
│     ┆     ┆     ┆ IEW ┆   ┆     ┆     ┆ UTY ┆     │
│     ┆     ┆     ┆ ICZ ┆   ┆     ┆     ┆ WNE ┆     │
│     ┆     ┆     ┆ -   ┆   ┆     ┆     ┆ GO  ┆     │
│     ┆     ┆     ┆ SZC ┆   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ ZUR ┆   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ EK  ┆   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ SP. ┆   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ Z   ┆   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ O.… ┆   ┆     ┆     ┆     ┆     │
│ 2   ┆ 202 ┆ -W/ ┆ POL ┆ … ┆ 202 ┆ 202 ┆ PUB ┆ AU  │
│     ┆ 3   ┆ IV- ┆ SKA ┆   ┆ 3-1 ┆ 3-0 ┆ LIK ┆     │
│     ┆     ┆ B/2 ┆ PRE ┆   ┆ 2-2 ┆ 9-1 ┆ ACJ ┆     │
│     ┆     ┆ 76/ ┆ SS  ┆   ┆ 0   ┆ 8   ┆ A   ┆     │
│     ┆     ┆ AU/ ┆ SP. ┆   ┆     ┆     ┆ NA  ┆     │
│     ┆     ┆ 3/2 ┆ Z   ┆   ┆     ┆     ┆ ZLE ┆     │
│     ┆     ┆ 023 ┆ O.O ┆   ┆     ┆     ┆ CEN ┆     │
│     ┆     ┆     ┆ .   ┆   ┆     ┆     ┆ IE  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ OBW ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ IES ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ZCZ ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ EŃ  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ W   ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ PRA ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ SIE ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ COD ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ZIE ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ …   ┆     │
│ 3   ┆ 202 ┆ -W/ ┆ AGO ┆ … ┆ 202 ┆ 202 ┆ PUD ┆ AU  │
│     ┆ 3   ┆ IV- ┆ RA  ┆   ┆ 3-0 ┆ 3-0 ┆ LIK ┆     │
│     ┆     ┆ B/2 ┆ S.A ┆   ┆ 2-0 ┆ 1-1 ┆ ACJ ┆     │
│     ┆     ┆ 0/A ┆ .   ┆   ┆ 3   ┆ 9   ┆ A   ┆     │
│     ┆     ┆ U/1 ┆     ┆   ┆     ┆     ┆ ODW ┆     │
│     ┆     ┆ /20 ┆     ┆   ┆     ┆     ┆ IES ┆     │
│     ┆     ┆ 23  ┆     ┆   ┆     ┆     ┆ ZCZ ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ EŃ  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ W   ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ PRA ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ SIE ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ COD ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ZIE ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ NNE ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ J O ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ZAS ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ IE… ┆     │
│ 4   ┆ 202 ┆ -W/ ┆ PBS ┆ … ┆ 202 ┆ 202 ┆ WYK ┆ AU  │
│     ┆ 3   ┆ IV- ┆ ERV ┆   ┆ 3-0 ┆ 3-0 ┆ ONA ┆     │
│     ┆     ┆ B/1 ┆ ICE ┆   ┆ 5-3 ┆ 4-2 ┆ NIE ┆     │
│     ┆     ┆ 29/ ┆ S.C ┆   ┆ 1   ┆ 6   ┆ KOP ┆     │
│     ┆     ┆ AU/ ┆ KAM ┆   ┆     ┆     ┆ ERT ┆     │
│     ┆     ┆ 2/2 ┆ IL  ┆   ┆     ┆     ┆ Z   ┆     │
│     ┆     ┆ 023 ┆ WYK ┆   ┆     ┆     ┆ NAD ┆     │
│     ┆     ┆     ┆ ROT ┆   ┆     ┆     ┆ RUK ┆     │
│     ┆     ┆     ┆ A,  ┆   ┆     ┆     ┆ IEM ┆     │
│     ┆     ┆     ┆ KRZ ┆   ┆     ┆     ┆ WRA ┆     │
│     ┆     ┆     ┆ YSZ ┆   ┆     ┆     ┆ Z Z ┆     │
│     ┆     ┆     ┆ TOF ┆   ┆     ┆     ┆ DOS ┆     │
│     ┆     ┆     ┆ PAW ┆   ┆     ┆     ┆ TAW ┆     │
│     ┆     ┆     ┆ ŁOW ┆   ┆     ┆     ┆ Ą   ┆     │
│     ┆     ┆     ┆ SKI ┆   ┆     ┆     ┆     ┆     │
│ 5   ┆ 202 ┆ -W/ ┆ PBS ┆ … ┆ 202 ┆ 202 ┆ DZI ┆ AU  │
│     ┆ 3   ┆ I/5 ┆ ERV ┆   ┆ 3-1 ┆ 3-0 ┆ ERŻ ┆     │
│     ┆     ┆ 53/ ┆ ICE ┆   ┆ 2-3 ┆ 1-3 ┆ AWA ┆     │
│     ┆     ┆ AU/ ┆ S.C ┆   ┆ 1   ┆ 1   ┆ UŻĄ ┆     │
│     ┆     ┆ 1/2 ┆ KAM ┆   ┆     ┆     ┆ DZE ┆     │
│     ┆     ┆ 023 ┆ IL  ┆   ┆     ┆     ┆ NI  ┆     │
│     ┆     ┆     ┆ WYK ┆   ┆     ┆     ┆ AKO ┆     │
│     ┆     ┆     ┆ ROT ┆   ┆     ┆     ┆ PER ┆     │
│     ┆     ┆     ┆ A,  ┆   ┆     ┆     ┆ TUJ ┆     │
│     ┆     ┆     ┆ KRZ ┆   ┆     ┆     ┆ ĄCE ┆     │
│     ┆     ┆     ┆ YSZ ┆   ┆     ┆     ┆ GO  ┆     │
│     ┆     ┆     ┆ TOF ┆   ┆     ┆     ┆ PIT ┆     │
│     ┆     ┆     ┆ PAW ┆   ┆     ┆     ┆ NEY ┆     │
│     ┆     ┆     ┆ ŁOW ┆   ┆     ┆     ┆ BOW ┆     │
│     ┆     ┆     ┆ SKI ┆   ┆     ┆     ┆ ES  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ DI3 ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ …   ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ … ┆ …   ┆ …   ┆ …   ┆ …   │
│ 599 ┆ 202 ┆ -W/ ┆ MIĘ ┆ … ┆ 202 ┆ 202 ┆ WYN ┆ WT  │
│ 3   ┆ 5   ┆ XII ┆ DZY ┆   ┆ 5-0 ┆ 5-0 ┆ AJE ┆     │
│     ┆     ┆ /3/ ┆ NAR ┆   ┆ 5-1 ┆ 3-0 ┆ M   ┆     │
│     ┆     ┆ WT/ ┆ ODO ┆   ┆ 1   ┆ 7   ┆ PRZ ┆     │
│     ┆     ┆ 2/2 ┆ WE  ┆   ┆     ┆     ┆ EST ┆     │
│     ┆     ┆ 025 ┆ CEN ┆   ┆     ┆     ┆ RZE ┆     │
│     ┆     ┆     ┆ TRU ┆   ┆     ┆     ┆ NI  ┆     │
│     ┆     ┆     ┆ M   ┆   ┆     ┆     ┆ KON ┆     │
│     ┆     ┆     ┆ KUL ┆   ┆     ┆     ┆ FER ┆     │
│     ┆     ┆     ┆ TUR ┆   ┆     ┆     ┆ ENC ┆     │
│     ┆     ┆     ┆ Y   ┆   ┆     ┆     ┆ YJN ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ EJ  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ WRA ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ Z Z ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ZAP ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ LEC ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ZE… ┆     │
│ 599 ┆ 202 ┆ -W/ ┆ KRA ┆ … ┆ 202 ┆ 202 ┆ WYN ┆ WT  │
│ 4   ┆ 5   ┆ XII ┆ KÓW ┆   ┆ 5-0 ┆ 5-0 ┆ AJE ┆     │
│     ┆     ┆ /2/ ┆ 502 ┆   ┆ 2-1 ┆ 2-1 ┆ M   ┆     │
│     ┆     ┆ WT/ ┆ 0   ┆   ┆ 7   ┆ 1   ┆ PRZ ┆     │
│     ┆     ┆ 1/2 ┆ SP. ┆   ┆     ┆     ┆ EZ  ┆     │
│     ┆     ┆ 025 ┆ Z   ┆   ┆     ┆     ┆ GMK ┆     │
│     ┆     ┆     ┆ O.O ┆   ┆     ┆     ┆ ORA ┆     │
│     ┆     ┆     ┆ . W ┆   ┆     ┆     ┆ Z   ┆     │
│     ┆     ┆     ┆ LIK ┆   ┆     ┆     ┆ AGE ┆     │
│     ┆     ┆     ┆ WID ┆   ┆     ┆     ┆ NCJ ┆     │
│     ┆     ┆     ┆ ACJ ┆   ┆     ┆     ┆ Ę   ┆     │
│     ┆     ┆     ┆ I,  ┆   ┆     ┆     ┆ WIN ┆     │
│     ┆     ┆     ┆ WIN ┆   ┆     ┆     ┆ DMI ┆     │
│     ┆     ┆     ┆ DMI ┆   ┆     ┆     ┆ LL  ┆     │
│     ┆     ┆     ┆ LL  ┆   ┆     ┆     ┆ DZI ┆     │
│     ┆     ┆     ┆ SPÓ ┆   ┆     ┆     ┆ AŁA ┆     │
│     ┆     ┆     ┆ …   ┆   ┆     ┆     ┆ JĄC ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ Ą…  ┆     │
│ 599 ┆ 202 ┆ -W/ ┆ AGE ┆ … ┆ 202 ┆ 202 ┆ WYN ┆ WT  │
│ 5   ┆ 5   ┆ XII ┆ NCJ ┆   ┆ 5-1 ┆ 5-1 ┆ AJE ┆     │
│     ┆     ┆ /30 ┆ A   ┆   ┆ 1-1 ┆ 0-1 ┆ M W ┆     │
│     ┆     ┆ /WT ┆ ROZ ┆   ┆ 5   ┆ 0   ┆ DNI ┆     │
│     ┆     ┆ /13 ┆ WOJ ┆   ┆     ┆     ┆ U   ┆     │
│     ┆     ┆ /20 ┆ U   ┆   ┆     ┆     ┆ 15  ┆     │
│     ┆     ┆ 25  ┆ MIA ┆   ┆     ┆     ┆ LIS ┆     │
│     ┆     ┆     ┆ STA ┆   ┆     ┆     ┆ TOP ┆     │
│     ┆     ┆     ┆ KRA ┆   ┆     ┆     ┆ ADA ┆     │
│     ┆     ┆     ┆ KOW ┆   ┆     ┆     ┆ 202 ┆     │
│     ┆     ┆     ┆ A   ┆   ┆     ┆     ┆ 5   ┆     │
│     ┆     ┆     ┆ SPÓ ┆   ┆     ┆     ┆ R.  ┆     │
│     ┆     ┆     ┆ ŁKA ┆   ┆     ┆     ┆ PRZ ┆     │
│     ┆     ┆     ┆ Z   ┆   ┆     ┆     ┆ EST ┆     │
│     ┆     ┆     ┆ OGR ┆   ┆     ┆     ┆ RZE ┆     │
│     ┆     ┆     ┆ ANI ┆   ┆     ┆     ┆ NI  ┆     │
│     ┆     ┆     ┆ CZ… ┆   ┆     ┆     ┆ CE… ┆     │
│ 599 ┆ 202 ┆ -W/ ┆ MCS ┆ … ┆ 202 ┆ 202 ┆ ZAK ┆ WT  │
│ 6   ┆ 5   ┆ IV- ┆ WIT ┆   ┆ 5-0 ┆ 5-0 ┆ UP  ┆     │
│     ┆     ┆ B/8 ┆ OLD ┆   ┆ 4-1 ┆ 3-1 ┆ AUT ┆     │
│     ┆     ┆ 2/W ┆ ROM ┆   ┆ 5   ┆ 4   ┆ ORS ┆     │
│     ┆     ┆ T/1 ┆ ANI ┆   ┆     ┆     ┆ KIC ┆     │
│     ┆     ┆ /20 ┆ SZY ┆   ┆     ┆     ┆ H   ┆     │
│     ┆     ┆ 25  ┆ N   ┆   ┆     ┆     ┆ PIN ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ÓW  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ (27 ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ 50  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ SZT ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ .)  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ Z   ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ MOT ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ YWA ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ MI  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ KRA ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ K…  ┆     │
│ 599 ┆ 202 ┆ -W/ ┆ SO  ┆ … ┆ 202 ┆ 202 ┆ ZAP ┆ WT  │
│ 7   ┆ 5   ┆ I/2 ┆ BRI ┆   ┆ 5-1 ┆ 5-0 ┆ LAN ┆     │
│     ┆     ┆ 489 ┆ GHT ┆   ┆ 0-3 ┆ 5-2 ┆ OWA ┆     │
│     ┆     ┆ /WT ┆ SPÓ ┆   ┆ 1   ┆ 8   ┆ NIE ┆     │
│     ┆     ┆ /34 ┆ ŁKA ┆   ┆     ┆     ┆ I   ┆     │
│     ┆     ┆ /20 ┆ Z   ┆   ┆     ┆     ┆ REA ┆     │
│     ┆     ┆ 25  ┆ O.O ┆   ┆     ┆     ┆ LIZ ┆     │
│     ┆     ┆     ┆ .   ┆   ┆     ┆     ┆ ACJ ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ A   ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ KAM ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ PAN ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ II  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ INF ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ORM ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ACY ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ JNO ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ - … ┆     │
└─────┴─────┴─────┴─────┴───┴─────┴─────┴─────┴─────┘

In [94]:
pl.Config.set_fmt_str_lengths(300)
pl.Config.set_tbl_width_chars(100)

(
    df_temp
    # .select(
    #     pl.col(_names.idx, _names.contractor_name, _names.nip)
    # )
    .with_columns(
        pl.col(_names.nip).str.contains('-').alias("contains_comma")
    )
    .filter(
        pl.col("contains_comma")
    )
    # .with_columns(
    #     pl.col(_names.contractor_name).str.split(','),
    #     pl.col(_names.nip).str.split(',')
    # )
    # .with_columns(
    #     pl.col(_names.contractor_name).list.len().cast(pl.Int64).alias("contractor_name_len"),
    #     pl.col(_names.nip).list.len().cast(pl.Int64).alias("nip_len"),
    #     abs(pl.col(_names.contractor_name).list.len().cast(pl.Int64) - pl.col(_names.nip).list.len().cast(pl.Int64)).alias("diff_len") #cast to Int64 or we get underflow
    # )
    # .filter(
    #     (pl.col("diff_len") != 0)
    #     & (pl.col("contractor_name_len") > pl.col("nip_len"))
    #     # & (pl.col("nip_len") == 2)
    # )
)

shape: (3_395, 12)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ idx  ┆ year_filen ┆ registry   ┆ contractor ┆ … ┆ date_contr ┆ contract_ ┆ administr ┆ contains_ │
│ ---  ┆ ame        ┆ ---        ┆ _name      ┆   ┆ act_signed ┆ desc      ┆ ative_uni ┆ comma     │
│ i64  ┆ ---        ┆ str        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ t         ┆ ---       │
│      ┆ i64        ┆            ┆ str        ┆   ┆ str        ┆ str       ┆ ---       ┆ bool      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ str       ┆           │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 20   ┆ 2023       ┆ -W/I/958/B ┆ WSZOŁEK    ┆ … ┆ 2023-03-08 ┆ REDAKCJA  ┆ BD        ┆ true      │
│      ┆            ┆ D/27/2023  ┆ GABRIELA   ┆   ┆            ┆ 7 NUMERÓW ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ GAZETKI   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ LOKALNEJ  ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DZIENICY  ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ XI        ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ PODGÓRZE  ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DUCHACKIE ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ W 2023 R. ┆           ┆           │
│ 22   ┆ 2023       ┆ -W/I/863/B ┆ GAWRON     ┆ … ┆ 2023-02-27 ┆ OPRACOWAN ┆ BD        ┆ true      │
│      ┆            ┆ D/25/2023  ┆ JAKUB      ┆   ┆            ┆ IE REDAKC ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ YJNE 7    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ NUMERÓW   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ GAZETKI   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ RADY I    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ ZARZĄDU   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DZIELNICY ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ IX ŁAGIEW ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ NIKI -    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ BOREK     ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ FAŁĘCKI,. ┆           ┆           │
│ 25   ┆ 2023       ┆ -W/I/828/B ┆ SZAFLARSKA ┆ … ┆ 2023-03-01 ┆ OBSŁUGA   ┆ BD        ┆ true      │
│      ┆            ┆ D/22/2023  ┆ ANNA       ┆   ┆            ┆ TABLIC    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ INFORMACY ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ JNYCH     ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ RADY      ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DZIELNICY ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ XI        ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ PODGÓRZE  ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DUCHACKIE ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ .         ┆           ┆           │
│ 27   ┆ 2023       ┆ -W/I/806/B ┆ CZAJA      ┆ … ┆ 2023-02-15 ┆ AKTUALIZA ┆ BD        ┆ true      │
│      ┆            ┆ D/20/2023  ┆ DAWID      ┆   ┆            ┆ CJA INFOR ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ MACJI W   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ MEDIACH   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ SPOŁECZNO ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ ŚCIOWYCH  ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ ORAZ REDA ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ GOWANIE   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ STRONY    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ INTERNETO ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ WEJ       ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DZIELNICY ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ VIII      ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DĘBNIKI.  ┆           ┆           │
│ 28   ┆ 2023       ┆ -W/I/792/B ┆ CZAJA      ┆ … ┆ 2023-02-15 ┆ OBSŁUGA   ┆ BD        ┆ true      │
│      ┆            ┆ D/19/2023  ┆ DAWID      ┆   ┆            ┆ TABLIC    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ INFORMACY ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ JNYCH     ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ RADY      ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DZIELNICY ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ VIII      ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DĘBNIKI   ┆           ┆           │
│ …    ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 5922 ┆ 2025       ┆ -W/I/767/W ┆ ZMYŚLONY   ┆ … ┆ 2025-02-21 ┆ PRZYGOTOW ┆ WT        ┆ true      │
│      ┆            ┆ T/7/2025   ┆ PIOTR      ┆   ┆            ┆ ANIE AUTO ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ RSKIEJ    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ KONCEPCJI ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ MERYTORYC ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ ZNEJ I    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ ZAŁOŻEŃ   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ PROGRAMOW ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ YCH KONFE ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ RENCJI    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ "MIASTA   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ HISTORYCZ ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ NE 3.0",  ┆           ┆           │
│ 5971 ┆ 2025       ┆ -W/I/3084/ ┆ WORLDWIDE  ┆ … ┆ 2025-08-06 ┆ UDZIAŁ W  ┆ WT        ┆ true      │
│      ┆            ┆ WT/46/2025 ┆ EVENTS     ┆   ┆            ┆ TARGACH   ┆           ┆           │
│      ┆            ┆            ┆ GROUP LTD  ┆   ┆            ┆ PRZEDSTAW ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ ICIELI    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ KRAKOWSKI ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ EGO BIURA ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ KONGRESÓW ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ /KRAKOW   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ CONVENTIO ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ N BUREAU  ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ PROMUJĄCY ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ CH KRAKÓW ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ I MAŁOPOL ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ SKĘ JAKO  ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DESTYNACJ ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ Ę MICE    ┆           ┆           │
│ 5972 ┆ 2025       ┆ -W/IV-B/16 ┆ CITY DESTI ┆ … ┆ 2025-06-25 ┆ USŁUGA    ┆ WT        ┆ true      │
│      ┆            ┆ 4/WT/3/202 ┆ NATIONS    ┆   ┆            ┆ WSTĘPU (W ┆           ┆           │
│      ┆            ┆ 5          ┆ ALLIANCE   ┆   ┆            ┆ RAMACH    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ TZW.      ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ OPŁATY    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ KONFERENC ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ YJNEJ)    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DLA P.    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ JAKUBA    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ CHMIELNIC ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ KIEGO -   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ PRACOWNIK ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ A         ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ WYDZIAŁU  ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DS.       ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ TURYSTYKI ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ NA WYDARZ ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ ENIE      ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ CITYDNA   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ SUMMER    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ SCHOOL    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ 2025 W    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ LUKSEMBUR ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ GU.W      ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DNIACH    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ 25-29SIER ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ PNIA 2025 ┆           ┆           │
│ 5973 ┆ 2025       ┆ -W/IV-B/18 ┆ INTERNATIO ┆ … ┆ 2025-07-30 ┆ USŁUGA    ┆ WT        ┆ true      │
│      ┆            ┆ 4/WT/5/202 ┆ NAL        ┆   ┆            ┆ WSTĘPU    ┆           ┆           │
│      ┆            ┆ 5          ┆ CONGRESS   ┆   ┆            ┆ TZW.      ┆           ┆           │
│      ┆            ┆            ┆ AND        ┆   ┆            ┆ OPŁATA    ┆           ┆           │
│      ┆            ┆            ┆ CONVENTION ┆   ┆            ┆ KONFERENC ┆           ┆           │
│      ┆            ┆            ┆ ASSOCIATIO ┆   ┆            ┆ YJNA NA   ┆           ┆           │
│      ┆            ┆            ┆ N          ┆   ┆            ┆ 64.       ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ KONGRES   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ ICCA 2025 ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ INTERNATI ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ ONAL      ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ CONGRESS  ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ AND CONVE ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ NTION ASS ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ OCIATION  ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ (ICCA)    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DLA P.    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ MAŁGORZAT ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ Y PRZYGÓR ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ SKIEJ-SKO ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ WRON ORAZ ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ P. MONIKI ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ POPIOŁEK  ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ PRACOWNIK ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ ÓW        ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ WYDZIAŁU  ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DS.       ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ TURYSTYKI ┆           ┆           │
│ 5982 ┆ 2025       ┆ -W/XII/15/ ┆ AGENCJA    ┆ … ┆ 2025-06-10 ┆ WYNAJEM   ┆ WT        ┆ true      │
│      ┆            ┆ WT/7/2025  ┆ ROZWOJU    ┆   ┆            ┆ POMIESZCZ ┆           ┆           │
│      ┆            ┆            ┆ MIASTA     ┆   ┆            ┆ EŃ        ┆           ┆           │
│      ┆            ┆            ┆ KRAKOWA    ┆   ┆            ┆ CENTRUM   ┆           ┆           │
│      ┆            ┆            ┆ SP. Z      ┆   ┆            ┆ KONGRESOW ┆           ┆           │
│      ┆            ┆            ┆ O.O., WMH  ┆   ┆            ┆ EGO ICE   ┆           ┆           │
│      ┆            ┆            ┆ PROJECT    ┆   ┆            ┆ KRAKÓW W  ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ ZWIĄZKU Z ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ WYDARZENI ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ EM PN.    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ "CITIES   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ FORUM     ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ KRAKÓW    ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ 2025" W   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ DN. 16-19 ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ CZERWCA   ┆           ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆ 2025 R.   ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [65]:
df_temp.filter(pl.col("idx") == 3865)

shape: (3, 11)
┌─────┬─────┬─────┬─────┬───┬─────┬─────┬─────┬─────┐
│ idx ┆ yea ┆ reg ┆ con ┆ … ┆ dat ┆ dat ┆ con ┆ adm │
│ --- ┆ r_f ┆ ist ┆ tra ┆   ┆ e_v ┆ e_c ┆ tra ┆ ini │
│ i64 ┆ ile ┆ ry  ┆ cto ┆   ┆ ali ┆ ont ┆ ct_ ┆ str │
│     ┆ nam ┆ --- ┆ r_n ┆   ┆ d_t ┆ rac ┆ des ┆ ati │
│     ┆ e   ┆ str ┆ ame ┆   ┆ o   ┆ t_s ┆ c   ┆ ve_ │
│     ┆ --- ┆     ┆ --- ┆   ┆ --- ┆ ign ┆ --- ┆ uni │
│     ┆ i64 ┆     ┆ str ┆   ┆ str ┆ ed  ┆ str ┆ t   │
│     ┆     ┆     ┆     ┆   ┆     ┆ --- ┆     ┆ --- │
│     ┆     ┆     ┆     ┆   ┆     ┆ str ┆     ┆ str │
╞═════╪═════╪═════╪═════╪═══╪═════╪═════╪═════╪═════╡
│ 386 ┆ 202 ┆ -W/ ┆ KRA ┆ … ┆ nul ┆ 202 ┆ WPÓ ┆ SZ  │
│ 5   ┆ 3   ┆ V/5 ┆ KOW ┆   ┆ l   ┆ 3-0 ┆ ŁPR ┆     │
│     ┆     ┆ 2/S ┆ SKA ┆   ┆     ┆ 4-2 ┆ ACA ┆     │
│     ┆     ┆ Z/3 ┆ AKA ┆   ┆     ┆ 0   ┆ W   ┆     │
│     ┆     ┆ 1/2 ┆ DEM ┆   ┆     ┆     ┆ OBS ┆     │
│     ┆     ┆ 023 ┆ IA  ┆   ┆     ┆     ┆ ZAR ┆     │
│     ┆     ┆     ┆ IM. ┆   ┆     ┆     ┆ ZE  ┆     │
│     ┆     ┆     ┆ AND ┆   ┆     ┆     ┆ OSÓ ┆     │
│     ┆     ┆     ┆ RZE ┆   ┆     ┆     ┆ B   ┆     │
│     ┆     ┆     ┆ JA  ┆   ┆     ┆     ┆ NIE ┆     │
│     ┆     ┆     ┆ FRY ┆   ┆     ┆     ┆ PEŁ ┆     │
│     ┆     ┆     ┆ CZA ┆   ┆     ┆     ┆ NOS ┆     │
│     ┆     ┆     ┆ MOD ┆   ┆     ┆     ┆ PRA ┆     │
│     ┆     ┆     ┆ RZE ┆   ┆     ┆     ┆ WNY ┆     │
│     ┆     ┆     ┆ WSK ┆   ┆     ┆     ┆ CH  ┆     │
│     ┆     ┆     ┆ …   ┆   ┆     ┆     ┆     ┆     │
│ 386 ┆ 202 ┆ -W/ ┆ ZAK ┆ … ┆ 202 ┆ 202 ┆ WYK ┆ OU  │
│ 5   ┆ 4   ┆ II/ ┆ ŁAD ┆   ┆ 4-0 ┆ 4-0 ┆ ONA ┆     │
│     ┆     ┆ 156 ┆ ELE ┆   ┆ 8-3 ┆ 7-1 ┆ NIE ┆     │
│     ┆     ┆ /OU ┆ KTR ┆   ┆ 0   ┆ 2   ┆ WYM ┆     │
│     ┆     ┆ /9/ ┆ OIN ┆   ┆     ┆     ┆ IAN ┆     │
│     ┆     ┆ 202 ┆ STA ┆   ┆     ┆     ┆ YWE ┆     │
│     ┆     ┆ 4   ┆ LAC ┆   ┆     ┆     ┆ WNĘ ┆     │
│     ┆     ┆     ┆ JES ┆   ┆     ┆     ┆ TRZ ┆     │
│     ┆     ┆     ┆ TOP ┆   ┆     ┆     ┆ NEJ ┆     │
│     ┆     ┆     ┆ KAK ┆   ┆     ┆     ┆ LIN ┆     │
│     ┆     ┆     ┆ RZY ┆   ┆     ┆     ┆ IZA ┆     │
│     ┆     ┆     ┆ SZT ┆   ┆     ┆     ┆ SIL ┆     │
│     ┆     ┆     ┆ OF  ┆   ┆     ┆     ┆ AJĄ ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ CEJ ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ DED ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ YKO ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ WA… ┆     │
│ 386 ┆ 202 ┆ -W/ ┆ FUN ┆ … ┆ 202 ┆ 202 ┆ REA ┆ SP  │
│ 5   ┆ 5   ┆ I/2 ┆ DAC ┆   ┆ 5-1 ┆ 5-0 ┆ LIZ ┆     │
│     ┆     ┆ 407 ┆ JA  ┆   ┆ 2-1 ┆ 5-2 ┆ ACJ ┆     │
│     ┆     ┆ /SP ┆ PIŁ ┆   ┆ 9   ┆ 0   ┆ A   ┆     │
│     ┆     ┆ /14 ┆ KAR ┆   ┆     ┆     ┆ ZAD ┆     │
│     ┆     ┆ 9/2 ┆ SKI ┆   ┆     ┆     ┆ ANI ┆     │
│     ┆     ┆ 025 ┆ KRA ┆   ┆     ┆     ┆ A   ┆     │
│     ┆     ┆     ┆ KÓW ┆   ┆     ┆     ┆ PUB ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ LIC ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ZNE ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ GO  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ PM: ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ "PI ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ ŁKA ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ RSK ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ IE  ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ MAR ┆     │
│     ┆     ┆     ┆     ┆   ┆     ┆     ┆ …   ┆     │
└─────┴─────┴─────┴─────┴───┴─────┴─────┴─────┴─────┘